project:
  type: website
  output-dir: docs
  
website:
  title: "Data Viz Collective"
  search: true
  reader-mode: true
  repo-url: "https://github.com/Aditya-Dahiya/projects_presentations"
  repo-actions: [edit, issue]
  site-url: "https://aditya-dahiya.github.io/projects_presentations/projects.html"
  description: "Aditya Dahiya"
  navbar:
    left:
      - href: presentations.qmd
        text: "Presentations"
      - href: projects.qmd
        text: "Projects"
      - href: data_vizs.qmd
        text: "Data Visualizations"
      - href: about.qmd
        text: "About Me"
    logo: "docs/aditya_dahiya_er_sheet.jpg"
    logo-alt: "Data Viz Collective"
    tools:
      - icon: rss
        href: index.xml
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/Aditya-Dahiya/projects_presentations
          - text: "Suggestions / Feedback"
            url:  https://github.com/Aditya-Dahiya/projects_presentations/issues
format:
  html: 
    theme: litera
    css: styles.css
    toc: true



