---
title: "Haunted Places in the United States"
author: "Aditya Dahiya"
editor: visual
subtitle: "Tidy Tuesday (Oct 10, 2023)"
date: "2023-10-10"
format:
  revealjs: 
    footer: "October 12, 2023"
    theme: white
    touch: true
    controls: true
    slide-number: true
    preview-links: auto
    css: styles.css
    transition: slide
    transition-speed: default
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    scrollable: true
    embed-resources: true
editor_options: 
  chunk_output_type: console
execute: 
  echo: false
  error: false
  message: false
  warning: false
---

Loading Libraries

```{r}
#| label: setup

# Loading libraries
library(tidyverse)      # the data manipulation package!
library(gt)             # beautiful tables
library(gtExtras)       # themeing the beautful tables
library(visdat)         # data overview visualization
library(janitor)        # cleaning the data and column names etc.
library(ggthemes)       # nice ggplot themes

# Reading in the data
haunted_places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-10-10/haunted_places.csv')

# Load the USA state boundaries data
usa_map <- map_data("state")


```

Study the data set

```{r}
#| label: exploratory-data-analysis
#| eval: false

haunted_places |>
  visdat::vis_dat()

# Load required packages
library(ggplot2)
library(maps)
library(ggmap)


n_distinct(haunted_places$city)

haunted_places |>
ggplot() +
  geom_polygon(data = usa_map, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "lightgrey", 
               color = "white") +
  geom_point(aes(x = longitude, y = latitude)) +
  coord_fixed(ratio = 1.3,
              xlim = c(-130, -70),
              ylim = c(25, 50)) +
  labs(title = "Haunted Places in USA") +
  theme_void()


# Create a ggplot object
ggplot(usa, aes(x = long, y = lat, group = group)) +
  geom_map(map = usa, aes(fill = "State"), color = "black") +
  expand_limits(x = usa$long, y = usa$lat) +
  scale_fill_manual(values = "lightblue", name = "State") +
  labs(title = "Map of USA with States") +
  theme_minimal()

# Display the map
gg


```
