---
title: "Interaction with IAS (OT)s 2023-25 batch - Secretariat Attachment"
author: "Dr. Aditya Dahiya, IAS"
format: 
  revealjs:
    transition: slide
    transition-speed: fast
    touch: true
    controls: true
    theme: simple
    scrollable: true
    navigation-mode: linear
    slide-number: h.v
date: "2024-04-15"
date-format: long
editor: visual
---

# Charges held currently

1.  Chief Executive Officer, Ayushman Bharat Haryana Health Protection Authority

2.  Mission Director, National Health Mission, Haryana

3.  State Mission Director, Ayushman Bharat Digital Mission

4.  Special Secretary, Health Department

5.  Special Secretary, Human Resources Department

6.  Special Secretary, General Administration Department

7.  Secretary, Central Committee of Examinations

# Ayushman Bharat - Haryana Health Protection Authority

## Introduction

-   Ayushman Bharat- Pradhan Mantri Jan Arogya Yojana Haryana is a flagship scheme of Government of India launched on 23rd September, 2018.
-   Aim: To holistically address healthcare services at secondary and tertiary level.
-   Features:
    -   World’s largest health insurance/assurance scheme fully financed by the Government.
    -   Provides health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization for entitled beneficiaries of SECC-2011 data.

## Number of beneficiaries

-   Guidelines: All the deprived families in SECC-2011 database were declared as the entitled beneficiaries of AB-PMJAY across the country.
-   Haryana Statistics:
    -   Total deprived families in SECC-2011 data: 15,51,798
    -   Identified families: 9,25,08
    -   Cards generated: 28,89,287
-   Expansion: Benefits extended to Antyodya families (approximately 45 Lakh including 1.70 crore beneficiaries) in Haryana.

## CHIRAYU Scheme (Comprehensive Health Insurance of Antyodaya Units)

-   Launch: "Extension of Ayushman Bharat to Antyodaya families through CHIRAYU scheme" by Hon’ble Chief Minister, Haryana on 21.11.2022.
-   Card Generation: Total of 1,15,04,640 Ayushman cards generated under AB-PMJAY, CHIRAYU, and CHIRAYU Extension scheme till 02.04.2024.
-   Fraud Prevention: Ayushman cards generated using PPP ID pre-seeded with UID.

## CHIRAYU Scheme

-   Budget Allocation:
    -   Under AB-PMJAY: Central Govt. and State Govt. share budget in 60:40 ratio.
    -   Under CHIRAYU Scheme: 100% budget provision by the State Government. Budget of Rs. 612 Crore sanctioned by Finance Department, State of Haryana for FY 2023-24.
-   Implementation:
    -   Data shared with National Health Authority, Govt. of India for integration of AB-PMJAY GoI portal with PPP ID.
    -   Cashless, paperless, transparent, digital, and IT driven scheme.

## CHIRAYU Scheme

-   Benefits:
    -   No cap in family size and age of family members.
    -   Covers all pre-existing diseases.
    -   All Health Benefit Packages (HBP) extended without changes.
    -   Around 2,200 treatment packages available.
    -   Covers treatment cost of investigations, hospitalization, and post-hospitalization expenses for medicines, etc.

## Extension of PMJAY-CHIRAYU Scheme

-   Extended to families with verified annual income above Rs. 1.80 upto Rs. 3 lakhs
-   CM Budget Speech Announcement (FY 2023-24):
    -   Extension of Ayushman Bharat-CHIRAYU scheme to families with verified annual family income above ₹1.80 lakh and upto ₹3.00 lakh upon nominal contribution of ₹1500/- per family per annum.
-   Progress:
    -   Families deposited nominal contribution: 56,451 (Till 03.04.2024)
    -   Card generation commenced: 01.11.2023
    -   Total cards generated: 1,02,900 (Till 02.04.2024)

## Highlights of the Scheme in Haryana:

-   Total Ayushman Cards Generated: 1,15,04,640
    -   SECC-2011: 28,89,287
    -   CHIRAYU: 85,12,394
    -   CHIRAYU Extension: 1,02,959
-   Hospitals Empaneled: 1178 (Public- 511, Private-667)
-   Total claims submitted: 12,89,033
-   Total claims amount submitted: Rs. 1,792.98 crore

## Achievements and Best practices:

-   1st State to launch AB-PMJAY in the country.
-   100% Aadhaar seeding of Ayushman Cards.
-   100% Biometric Authentication at the time of hospitalization.
-   Fastest Claims Processing State: Appreciation letter from CEO NHA, GoI.
-   100% quality closure of grievances: Appreciated by CEO, NHA.

## Implementation of Comprehensive Cashless Health Facility (CCHF):

## Category-I beneficiaries:

-   Scheme launch: 01.11.2023 (Department of Horticulture and Department of Fisheries in Trust Mode)
-   Extension: 01.01.2024 (All employees in the State and families/dependents of employees of Horticulture and Fisheries)
-   Total cards generated: 35,162 (Till 02.04.2024)
-   Approval:
    -   Draft notification of the scheme sent to the Govt.
    -   PPP ID linkage with Comprehensive Cashless Health Facility (CCHF) approved by the Govt.

## Category-II beneficiaries:

-   Approval: Hon’ble CM (08.08.2023)
-   Approval by Finance Department: 23.11.2023
-   Decision pending on inclusion in CCHF or CHIRAYU extension.

# National Health Mission (NHM), Haryana

## Overall Financials {.smaller}

The detail of year-wise budget approved and expenditure (Figures in Crore)

| Sr. No. | Year    | RoP/Approval    | Budget Received | Expenditure | \% Utilization |
|---------|---------|-----------------|-----------------|-------------|----------------|
| 1       | 2012-13 | 413.8           | 388.60          | 368.00      | 95%            |
| 2       | 2013-14 | 514.74          | 416.05          | 468.27      | 113%           |
| 3       | 2014-15 | 531.65          | 379.75          | 486.13      | 128%           |
| 4       | 2015-16 | 573.46          | 482.94          | 488.16      | 101%           |
| 5       | 2016-17 | 523.65          | 508.49          | 488.17      | 96%            |
| 6       | 2017-18 | 635.66          | 494.19          | 534.25      | 108%           |
| 7       | 2018-19 | 815.81          | 743.10          | 659.65      | 89%            |
| 8       | 2019-20 | 999.96          | 768.77          | 747.21      | 97%            |
| 9       | 2020-21 | 1139.78         | 921.20          | 806.05      | 88%            |
| 10      | 2021-22 | 1331.90         | 903.98          | 880.82      | 97%            |
| 11      | 2022-23 | 1443.14         | 938.65          | 990.28      | 105%           |
| 12      | 2023-24 | Till Jan., 2024 | 1440.26         | 638.20      | 610.18         |

## Maternal Health

-   Current Maternal Mortality Ratio (MMR) of Haryana: 110 (SRS-2018-20). Promotion of Institutional deliveries: Increased to 97.8% till January -2024 (HMIS).
-   Operationalization of 56 First Referral Units (FRUs) for emergency Obstetric care services.
-   Surakshit Janani Maah (SJM) celebrated in April-May, 2023.
    -   More than 76000 pregnant women examined.
    -   Around 16000 identified as high-risk pregnancies.

## Maternal Health

-   Availability of free Injection Iron Sucrose for treatment of severe Anaemia in pregnant ladies.
-   eSanjeevaniOPD: Online Stay Home OPD under National Tele - Consultation services of Govt. of India.
    -   Initiated in Haryana since 01.05.2020.
    -   Available 24X7 since 16.08.2021.

## Maternal Health {.smaller}

-   Establishment of specialized MCH Wings:
    -   6 specialized separate MCH Wings to be established in the state.
    -   Construction ongoing for MCH Panchkula and Panipat.
    -   2 new MCH Wings approved at Sirsa and Kaithal.
-   Establishment of Obstetric High Dependency Unit (HDU) and Intensive Care Unit (ICU):
    -   Sanction accorded by GoI at 5 Govt. /Govt. aided Medical colleges.
    -   05 Obs HDU/ICUs functional.

## Child Health {.smaller}

-   Infant Mortality Rate (IMR) of Haryana: 28 per 1000 live births (SRS 2020), decreased by 13 points since 2013 (IMR-41 in 2013).
-   Under Five mortality Rate (U5MR): Declined by 12 points from 45 (SRS 2013) to 33 (SRS 2020).

| Functional                        | Units |
|-----------------------------------|-------|
| Special Newborn Care Unit (SNCU)  | 24    |
| Kangaroo Mother Care Units (KMCU) | 66    |
| Newborn Stabilization Unit (NBSU) | 439   |
| Newborn Care Corner (NBCC)        | 11    |

## Child Health

-   Special Newborn Care Unit (SNCU):
    -   Total 26,861 newborns admitted in FY 2022-23 in 24 SNCUs.
    -   Total 23362 newborns admitted in 24 SNCUs from April 2023-January 2024.
-   Vitamin A supplementation round: 18.2 lakh children received vitamin A dose in May-June 2023.
-   Micronutrient Supplementation Program (MSP): Approx. 24.3 lakh IFA syrup bottles provided to targeted 6-59 month children in May 2023.

## Child Health

-   Intensified Diarrhoea Control Fortnight (IDCF): 27,000 children treated with Tab Zinc and ORS in July 2023. Approx. 25 Lakhs under five children distributed ORS packets.
-   Mother Absolute Affection (MAA) program: Sensitization of pregnant & lactating women on breastfeeding practices.
-   Emergency Covid Response Package (ECRP-II): Pediatric care units including HDU/ICU established in 20-district hospital of Haryana.

## Routine Immunization

-   NFHS-5 Routine Immunization coverage: Increased to 77% compared to 62% in NFHS-4.
-   FY 2022-23:
    -   Fully Immunized Children (FIC): 94% with 5.47 lac beneficiaries vaccinated against a target of 5.8 lac beneficiaries.
-   FY 2023-24 (till January 2024):
    -   FIC: 92% with 4.5 lac beneficiaries vaccinated against a target of 4.9 lac beneficiaries.

## Routine Immunization

-   Intensified Mission Indradhanush (IMI):
    -   IMI 4.0: 3 districts, 6274 sessions, 69835 children, 19203 pregnant women immunized.
    -   IMI 5.0: 3 rounds, total 1,95,268 children and 44,895 pregnant women vaccinated.
-   National Immunization Days (NID): Approx. 3600384 children given polio drops in March 2024.

## Routine Immunization {.smaller}

-   Sub-National Immunization Days (SNID):
    -   May 2023: 1486324 children in 6 districts given polio drops.
    -   Dec 2023: 1522197 children in 6 districts given polio drops.
-   Special Immunization week: Conducted quarterly in all districts.
-   Measles Rubella campaign: Conducted from 6th February to 31st March with 99% coverage.
-   UWIN (Winning over Universal Immunization): Digital solution for Universal Immunization Program (UIP) by MoHFW.

## Referral Transport Scheme

## Introduction

-   Initiated on 14th November 2009. All districts of Haryana covered. Total Ambulances: 588.
    -   55 Advance Life Support
    -   259 Basic Life Support
    -   239 Patient Transport
    -   29 Kilkari/Back to home
    -   6 Neonatal
-   Response time: **12 minutes**. Drop in time: **32 minutes**

## Free transportation services provided for:

-   Any patient in emergency
-   Pregnant women
-   Victims of roadside accidents
-   Post-natal cases (emergency till 6 weeks after delivery)
-   Sick infants and children up to 5 years

## Free transportation services provided for:

-   Severe Acute Malnourished (SAM) Children
-   Haemophilia and Thalassaemia patients during blood transfusion
-   Women after delivery
-   Freedom fighters/Ex-servicemen to Military Hospital
-   Mental/psychiatric emergencies
-   Inter-facility transportation

## Charges for emergency transportation:

-   BLS ambulances: Rs. 7 per km
-   ALS/Neonate Care Ambulances: Rs. 15 per km

## Manpower:

-   Fleet Manager: 1
-   Control Room Operator: 4
-   EMT: 3
-   Drivers:
    -   BLS, ALS & Neonate Ambulances: 3 each
    -   PTA: 3
    -   Kilkari ambulances: 1

## Achievement (2023-24 till Mar 12, 2024): {.smaller}

| Year    | Total Cases | Pregnant Women | Referral | Road Side Accident | Back Home | Sick Child | Sick Neonate | Other Cases |
|---------|-------------|----------------|----------|--------------------|-----------|------------|--------------|-------------|
| 2023-24 | 411120      | 213381         | 86397    | 27785              | 27446     | 3624       | 1467         | 49702       |

## Adolescent Health (AH)

## RASHTRIYA KISHOR SWASTHYA KARYAKRAM (RKSK) {.smaller}

-   WIFS IFA tablet: 80.6% children consumed WIFS IFA Blue tablet from April to Dec 2023.
-   National De-worming Day: Conducted on 15th February 2024.
-   Menstrual Hygiene Scheme: Provided sanitary napkin packets to rural adolescent girls and ASHAs.
-   Adolescent Friendly Health Clinics (AFHCs)/Mitrata Clinics: Functional at various levels.
-   School Health and Wellness Programme (SHWP): Trained teachers as Health and Wellness Ambassadors.

## RASHTRIYA BAL SWASTHYA KARYAKRAM (RBSK)

-   Early identification and intervention for children (birth to 18 years).

#### Screening:

-   Newborn screening at health facilities and home visits.
-   Mobile Health Teams for children (6 weeks-18 years).
-   Biannual screening in Anganwadis and schools.

## RASHTRIYA BAL SWASTHYA KARYAKRAM (RBSK)

#### Referral and Management:

-   District Early Intervention Centre (DEIC) established at Civil Hospital Level.
-   Financial aid for selected conditions.
-   Referral to Govt. and private empanelled health facilities.
-   MoU with Smile Train Clinics for cleft lip/palate treatment.
-   Surgical management for clubfoot.

## RASHTRIYA BAL SWASTHYA KARYAKRAM (RBSK)

### Achievements:

-   Health screening of around 35-40 Lakh children annually.
-   Approx. 5.3 Lakh children availed treatment services from April to Dec 2023.
-   Approx. 1.24 Lakh New and Follow up cases availed services at DEIC.
-   Financial support of Rs 6.65 Cr given to RBSK beneficiaries for treatment.

## National Urban Health Mission (NUHM)

## Introduction

-   Launched in May 2013 under NHM. Focus on urban poor population, including slum dwellers, homeless, etc.
-   Services provided through Urban Primary Health Centres (UPHCs).
-   107 UPHCs operational in Haryana.
-   Staffing: 1 M.O, 1 Staff Nurse, 1 Pharmacist, 1 Lab Technician, 1 Information Assistant, 1 Class-IV cum sweeper, 4-5 ANMs, and 1 Urban ASHA per 1500-2000 slum population.

## Services provided:

-   OPD Services
-   Routine Immunization Sessions
-   Ante Natal Registration and ANC
-   Referral Services
-   Basic Laboratory Services
-   Counselling services
-   Services for non-communicable diseases
-   Social mobilization and community level activities

## Activities and Achievements

-   Upgradation to Health and Wellness Centers (HWC) at all UPHCs.
-   E-sanjeevani tele-consultation services initiated.
-   Urban Health Nutrition Day celebrated twice monthly.
-   Special Outreach Camps providing specialist services.
-   Intersectoral convergence with Urban Local Bodies.

## Activities and Achievements

-   Recognition for best practices in national summits.
-   Meraaspataal integrated for patient feedback.
-   NQAS certification for quality assurance.
-   Kayakalp implementation for cleanliness.
-   Provision of specialist services at UPHCs.
-   Urban Health and wellness centers establishment.
-   Support for diagnostic infrastructure.

## Community Processes

## Accredited Social Health Activist (ASHA) & Community Health Officers (CHO) {.smaller}

-   Total 20374 ASHA enrolled against a target of 20676.
-   Monthly honorarium increased to Rs. 6100, highest in the country.
-   Provision of Rs. 2.00 lakh at the time of relieving for ASHA.
-   Compensatory grant of Rs. 3.00 lakh each provided to families of deceased ASHA.
-   Making golden cards for free treatment under Ayushman Bharat.

## Ayushman Bharat-Health & Wellness Centres (AB-HWCs)

## Introduction

-   Deliver Comprehensive Primary Health Care under Ayushman Bharat.
-   Expanded range of services closer to the community.
-   Services include care in pregnancy, neonatal and infant health care, family planning, management of diseases, emergency medical services, etc.

## Key Points {.smaller}

-   Additional human resource provision for Sub Health Centre level HWCs.
-   Total 1570 Community Health Officers (BAMS/BSc. Nursing with 6-month certificate course) working.
-   2668 AB-HWCs operational, including Sub Centres, Rural PHCs, Urban PHCs, and UHWCs.
-   All standalone Rural-PHCs and Sub Centres transformed into HWCs in Mewat/Nuh.
-   E-Sanjeevani Tele-consultation services initiated, with 342233 consultations conducted till date.
-   NQAS Certification for HWCs underway, with 45 SC HWCs targeted.
-   Kayakalp Awards won by PHCs and SHCs for FY 2022-23.
-   Adoption status of AB-HWC App is 98%.
-   HWCs' staff played a significant role in COVID-19 management.

## Administration Division (N.H.M.)

## Financial Assistance Announcement

-   Hon'ble CM announced financial assistance of Rs. 5000/- to NHM and NUHM workers.
-   Payment issued to 12650 workers out of 12672 sanctioned.
-   Data verification ongoing for remaining workers.

## Health Indicators (Haryana vs. India)

## Neonatal Mortality Rate (NMR) and Infant Mortality Rate (IMR) {.smaller}

| SR. NO. | INDICATOR WITH SOURCE         | Haryana (2013-14) | Haryana (2020-23) | India (2020)  |
|---------|-------------------------------|-------------------|-------------------|---------------|
| 1       | Neonatal Mortality Rate (NMR) | 26 (SRS 2013)     | 19 (SRS 2020)     | 20 (SRS 2020) |
| 2       | Infant Mortality Rate (IMR)   | 41 (SRS 2013)     | 28 (SRS 2020)     | 28 (SRS 2020) |

## Maternal Mortality Ratio and First Referral Unit {.smaller}

| SR. NO. | INDICATOR WITH SOURCE     | Haryana (2011-13)                       | Haryana (2018-20)                       | India (2020)     |
|---------|---------------------------|-----------------------------------------|-----------------------------------------|------------------|
| 3       | Maternal Mortality Ratio  | 127 (SRS 2011-13)                       | 110 (SRS 2018-20)                       | 97 (SRS 2018-20) |
| 4       | First Referral Unit (FRU) | 40 (including 2 urban FRU in Faridabad) | 56 (including 2 urban FRU in Faridabad) | \-               |

## Under-5 Mortality Rate and Sex Ratio at Birth {.smaller}

| SR. NO. | INDICATOR WITH SOURCE    | Haryana (2013) | Haryana (2020)      | India (2020)  |
|---------|--------------------------|----------------|---------------------|---------------|
| 5       | Under-5 Mortality Rate   | 45 (SRS 2013)  | 33 (SRS 2020)       | 32 (SRS 2020) |
| 6       | Sex Ratio at Birth (CRS) | 868 (CRS 2013) | 917 (upto Feb 2024) | \-            |

## Institutional Delivery, Full Immunization, ASHA {.smaller}

| SR. NO. | INDICATOR WITH SOURCE    | Haryana (2017) | Haryana (Jan. 2024)          | India (Jan. 2023) |
|---------|--------------------------|----------------|------------------------------|-------------------|
| 7       | Institutional Delivery   | 90.37% (HMIS)  | 97.1% (HMIS Jan. 2024)       | \-                |
| 8       | Full Immunization (HMIS) | 85.7%          | 92.6%                        | 92%               |
| 9       | ASHA                     | 16861 (92.67%) | 20380 (98.57% upto Dec 2023) | \-                |

## Newborn Care {.smaller}

| SR. NO. | INDICATOR WITH SOURCE             | Haryana (2017) | Haryana (Jan. 2024) | India (Jan. 2023) |
|---------|-----------------------------------|----------------|---------------------|-------------------|
| 10      | Special Newborn Care Units (SNCU) | 15             | 24 (2022-23)        | \-                |
| 11      | Newborn Stabilizing Units (NBSU)  | 52             | 66 (2022-23)        | \-                |
| 12      | Newborn Care Corners (NBCC)       | 192            | 439 (2022-23)       | \-                |

# Health Department (Special Secretary)

## Health: Administrative Department

1.  Adulteration of foodstuffs and other goods.
2.  Blood Transfusion Service and Blood Transfusion Centers in the State.
3.  Drugs and poisons and objectionable advertisements relating to drugs and medicines.
4.  Establishment matters relating to officers and staff under the administrative control of the Department except matters allotted to the General Administration Department.
5.  Family Planning.

## Health: Administrative Department

6.  Grant-in-aid to local bodies (for hospitals and dispensaries, Ayurvedic Aushdhaliyas, and other institutions).
7.  Hospitals, Dispensaries, Primary and Rural Health Centers.
8.  Infectious diseases, hospitals for their treatment and other measures for their suppression.
9.  Lunacy and mental deficiency including places for the reception or treatment of lunatics and mentally deficient individuals.
10. Medical attendance on Government servants and their families.

## Health: Administrative Department

11. Maternity and child welfare.
12. Medical inspection of school children.
13. Prohibition of inoculation and making the Primary vaccination and revaccination of children compulsory.
14. Prohibition of smoking in Cinema Halls.
15. Public Health, Epidemic Diseases, and Sanitation.

## Health: Administrative Department

16. Registration of births and deaths.
17. Supply of unclaimed bodies of deceased persons to hospitals and medical and teaching institutions for therapeutic purposes or for the purpose of anatomical operation and research work.
18. The Homoeopathic system of medicine.
19. The Indigenous systems of medicine.

# Human Resources Department (Special Secretary)

-   5 Branches / Divisions: HR-I, HR-II, HR-III, CC-I, CC-II

## HR-I Branch

## HR-I Branch Responsibilities

-   Probation, Confirmation, Determination of seniority, Departmental Test and SETC
-   Promotion Policy including all matters pertaining to promotion
-   Online Transfer Policy
-   Premature Retirement
-   Annual Confidential Reports
-   Adverse Remarks

## HR-I Branch Responsibilities

-   Conduct Rules
-   All matters pertaining to Code of Conduct
-   Moral Turpitude
-   Sexual Harassment
-   Suspension etc.
-   All matters pertaining to Punishment & Appeal Rules

## HR-I Branch Responsibilities

-   Memorials
-   Petitions
-   LTC Policy
-   Gazetted Holidays
-   Examine the cases of Departments of which FD is AD involving financial liability
-   Re-employment and Extension beyond the age of

## HR-II Branch

## HR-II Branch Responsibilities

-   CET Policy
-   Recruitment Policy
-   Socio Economic Criteria
-   Waiting list
-   Joining time on direct recruitment
-   Ex-gratia Policy
-   All kinds of Compassionate Appointments

## HR-III Branch

## HR-III Branch: Conditions Before Joining

-   Character and antecedent verification
-   Medical Certificate of Fitness
-   Fixation of Age for entry into Govt. service
-   Minimum qualification for entry into service
-   Classification of Posts
-   Up-gradation of Post
-   Outsourcing Policy

## HR-III Branch: Resignation and Reservation

-   Resignation from service
-   Reservation Policy
-   Certificates of reserved category candidates
-   Domicile Certificates

## HR-III Branch: Special Benefits and Incentives

-   All matter pertaining to certain benefits admissible to the categories employees or other employees including Pw Outstanding Sports Persons, etc.
-   Additional increments, incentive, award etc.

## HR-III Branch: Miscellaneous Matters

-   Special Casual Leave
-   Outsourcing Policy
-   Haryana Kaushal Rozgar Nigam
-   Fixation/Revision of Nigam Wage Rates(DC Rates)
-   Military Service Benefits
-   Including RTI cases on above matters.

## CC-I & II Branches

## CC-I Branch Responsibilities

-   Establishment of Common Cadre Group D Employees
-   All cases pertaining to establishment of Common Cadre group D Employees from Joining to retirement.
-   Implementation of and amendment in Group D Act, 2018.
-   Including RTI cases above matters.

## CC-II Branch Responsibilities

-   Establishment of Common Cadre Group C Employees
-   All cases pertaining to establishment of Common Cadre Group C Employees, i.e. from joining to retirement.
-   Drafting of Group C Bill.
-   Including RTI cases on above matters.

# General Administration Department

## Monitoring and Coordination Branch

-   Monitoring of Hon'ble CM Announcements
-   North Zonal Council Matters
-   Inter-State Coordination Issues
-   All miscellaneous and coordiantion matters by Chief Secretary
-   Monitoring of projects \> Rs. 100 cr.

## Recruitment Bodies

All establishment and policy matters of

-   Haryana Public Service Commission

-   Haryana Staff Selection Commission

## Administrative Reforms Branch {.smaller}

1.  All matters concerning Administrative Reforms in the departments of the Government and introduction of Organization and Methods work.
2.  All matters relating to Administrative Reforms Commission and follow up action on its reports.
3.  Associations of Government employees-Policy regarding.
4.  Classification of Offices.
5.  Inspection for delay checking and other administrative lapses in various departments.

## Administrative Reforms Branch {.smaller}

6.  Joint Consultative Machinery for Government employees.
7.  Policy regarding Records Management in Government departments.
8.  Revision and updating of Secretariat instructions and Office Manuals.
9.  Work study of various departments of Government for assessing staff requirements.
10. Right to Information Act, 2005 (Act 22 of 2005).
11. All matters relating to the State Information Commission.
12. Preparation and implementation of Citizen's charters of departments.

# Secretary, Central Committee of Examinations

## Departmental Examinations

For the following officers:

-   IAS (OT)s: Assistant Commissioners (Under Training)
-   HCS(EB) (OT)s: Extra Assistant Commissioners (Under Training)

**Confidential Branch**.

Each year, planned around June - July.

# Thank you.
